"""
Extra question banks for Passaroo:
- 7 state-specific DKT variants (VIC, QLD, WA, SA, ACT, TAS, NT)
  (NSW already exists as DKT_QUESTIONS in seed_data.py)
- 4 work-licence categories: White Card, RCG/Gaming, Security, Forklift

All questions are ORIGINAL, paraphrased, and written from publicly known
learning objectives. NOT copied from official government exams.
"""

# ====================================================================
# Driver Knowledge Test variants per state/territory
# ====================================================================

# Common road-rule items, paraphrased per state context.
# Each list contains ~10 starter questions per state.

DKT_VIC_QUESTIONS = [
    {"topic": "Hook Turns", "difficulty": "medium", "state": "VIC",
     "question": "In central Melbourne, a hook turn requires you to:",
     "options": ["Turn right from the left lane when allowed", "Turn left from the right lane",
                 "Make a U-turn at the intersection", "Stop and wait for a green arrow"],
     "correct": 0, "explanation": "Hook turns let you turn right from the leftmost lane at signposted CBD intersections, used to keep tram tracks clear."},
    {"topic": "Speed Limits", "difficulty": "easy", "state": "VIC",
     "question": "The default speed limit in a built-up area of Victoria, unless signed otherwise, is:",
     "options": ["40 km/h", "50 km/h", "60 km/h", "70 km/h"],
     "correct": 1, "explanation": "50 km/h is the default urban speed limit in VIC built-up areas."},
    {"topic": "Trams", "difficulty": "medium", "state": "VIC",
     "question": "When a tram stops to let passengers on or off and there is no safety zone, you must:",
     "options": ["Pass at any safe speed", "Stop and not move until passengers have finished and the tram doors close",
                 "Sound your horn", "Drive around on the right"],
     "correct": 1, "explanation": "You must stop level with the rear of the tram and wait until passengers finish and doors close."},
    {"topic": "P-plates", "difficulty": "medium", "state": "VIC",
     "question": "A Victorian P1 (red P) driver:",
     "options": ["May carry any number of peer passengers",
                 "Cannot carry more than one passenger aged 16–22 between 11pm and 5am (with exceptions)",
                 "Has no passenger restrictions", "Must drive with an experienced driver at all times"],
     "correct": 1, "explanation": "VIC P1 drivers face peer-passenger restrictions to reduce risk on the road."},
    {"topic": "Alcohol & Drugs", "difficulty": "easy", "state": "VIC",
     "question": "Learner and probationary drivers in Victoria must maintain a blood alcohol concentration of:",
     "options": ["0.00%", "0.02%", "0.05%", "Below the general limit"],
     "correct": 0, "explanation": "Learners and probationary drivers must have zero alcohol in their blood."},
    {"topic": "Mobile Phones", "difficulty": "easy", "state": "VIC",
     "question": "A learner driver in Victoria may use a mobile phone while driving:",
     "options": ["Hands-free only", "For navigation only", "Not at all", "Only when stopped at lights"],
     "correct": 2, "explanation": "Learners and P1 drivers must not use a mobile phone at all while driving in Victoria."},
    {"topic": "Roundabouts", "difficulty": "medium", "state": "VIC",
     "question": "Entering a multi-lane roundabout going straight ahead, you should generally use:",
     "options": ["The right lane only", "Either lane unless signs or markings dictate otherwise",
                 "The shoulder", "Reverse before entering"],
     "correct": 1, "explanation": "Use either lane unless arrows or signs require a specific lane for your intended direction."},
    {"topic": "School Zones", "difficulty": "easy", "state": "VIC",
     "question": "A common school speed zone in Victoria during posted hours is:",
     "options": ["20 km/h", "30 km/h", "40 km/h", "60 km/h"],
     "correct": 2, "explanation": "Most Victorian school speed zones are 40 km/h during the posted times."},
    {"topic": "Emergency Vehicles", "difficulty": "easy", "state": "VIC",
     "question": "If an emergency vehicle approaches with lights and sirens, you must:",
     "options": ["Continue at the same speed", "Move out of the way safely and give way",
                 "Stop immediately wherever you are", "Sound your horn"],
     "correct": 1, "explanation": "Move left and let it pass when it is safe to do so."},
    {"topic": "Demerit Points", "difficulty": "medium", "state": "VIC",
     "question": "VIC learner and probationary drivers can lose their licence if they accumulate:",
     "options": ["3 demerit points or more in 12 months",
                 "5 demerit points or more in 12 months",
                 "7 demerit points or more in 12 months",
                 "13 demerit points or more in 12 months"],
     "correct": 1, "explanation": "L and P drivers in VIC may face suspension at 5 or more demerit points in any 12-month period."},
]

DKT_QLD_QUESTIONS = [
    {"topic": "Speed Limits", "difficulty": "easy", "state": "QLD",
     "question": "The default speed limit in built-up areas of Queensland (unless signed) is:",
     "options": ["40 km/h", "50 km/h", "60 km/h", "80 km/h"],
     "correct": 1, "explanation": "50 km/h is the default urban speed limit in QLD."},
    {"topic": "Roadworks", "difficulty": "easy", "state": "QLD",
     "question": "When driving through roadworks in QLD where workers are present, you must:",
     "options": ["Maintain your speed", "Follow the posted lower speed limit and obey signal flaggers",
                 "Sound your horn continuously", "Use hazard lights and continue"],
     "correct": 1, "explanation": "Always obey roadwork signs and slow down for the safety of workers."},
    {"topic": "P-plates", "difficulty": "medium", "state": "QLD",
     "question": "A Queensland P1 driver under 25 is subject to which night-time peer passenger rule?",
     "options": ["No restrictions",
                 "May not carry more than one passenger under 21 (not immediate family) between 11pm and 5am",
                 "Must not drive after 9pm at all",
                 "Must not drive with anyone in the car"],
     "correct": 1, "explanation": "QLD P1 drivers under 25 face limits on carrying multiple young passengers late at night."},
    {"topic": "Mobile Phones", "difficulty": "easy", "state": "QLD",
     "question": "QLD open-licence drivers may use a mobile phone while driving:",
     "options": ["Only hands-free or mounted for calls and navigation",
                 "Freely held in their hand",
                 "Only on highways", "Only for text messages"],
     "correct": 0, "explanation": "Open-licence drivers may use a hands-free or properly mounted phone only — never held."},
    {"topic": "Alcohol & Drugs", "difficulty": "easy", "state": "QLD",
     "question": "The legal BAC limit for a fully licensed (open) driver in Queensland is below:",
     "options": ["0.00%", "0.02%", "0.05%", "0.10%"],
     "correct": 2, "explanation": "0.05% is the limit for open-licence drivers; learners and P drivers must be 0.00%."},
    {"topic": "Following Distance", "difficulty": "medium", "state": "QLD",
     "question": "On a wet QLD highway, your following distance should be:",
     "options": ["The same as in dry conditions",
                 "Doubled to at least four seconds",
                 "Halved", "Six car lengths"],
     "correct": 1, "explanation": "Wet roads need at least double the gap (about 4 seconds) to brake safely."},
    {"topic": "Roundabouts", "difficulty": "medium", "state": "QLD",
     "question": "At a roundabout, you must give way to vehicles:",
     "options": ["Approaching from your left", "Already in the roundabout",
                 "Larger than yours", "Behind you"],
     "correct": 1, "explanation": "Always give way to vehicles already in a roundabout when entering."},
    {"topic": "School Zones", "difficulty": "easy", "state": "QLD",
     "question": "A typical QLD school zone speed limit during posted hours is:",
     "options": ["20 km/h", "30 km/h", "40 km/h", "60 km/h"],
     "correct": 2, "explanation": "QLD school zones are usually 40 km/h during posted school hours."},
    {"topic": "Cyclists", "difficulty": "medium", "state": "QLD",
     "question": "When passing a cyclist on a QLD road with a speed limit of 60 km/h, you must allow at least:",
     "options": ["50 cm", "1 metre", "1.5 metres", "2 metres"],
     "correct": 1, "explanation": "1 metre minimum where the limit is 60 km/h or less; 1.5 m where it is higher."},
    {"topic": "Headlights", "difficulty": "easy", "state": "QLD",
     "question": "Headlights must be used in Queensland:",
     "options": ["Only when raining heavily",
                 "Between sunset and sunrise, and whenever visibility is reduced",
                 "Only on highways at night", "Whenever you choose"],
     "correct": 1, "explanation": "Use headlights from sunset to sunrise and any other time visibility is poor."},
]

DKT_WA_QUESTIONS = [
    {"topic": "Speed Limits", "difficulty": "easy", "state": "WA",
     "question": "The default speed limit in a built-up area of WA, unless signs say otherwise, is:",
     "options": ["40 km/h", "50 km/h", "60 km/h", "70 km/h"],
     "correct": 1, "explanation": "50 km/h is the default urban speed limit in WA."},
    {"topic": "Alcohol & Drugs", "difficulty": "easy", "state": "WA",
     "question": "WA novice drivers (L and P) must have a BAC of:",
     "options": ["0.00%", "0.02%", "0.05%", "Below the open limit"],
     "correct": 0, "explanation": "Novice drivers in WA must have zero alcohol in their blood."},
    {"topic": "Mobile Phones", "difficulty": "easy", "state": "WA",
     "question": "Touching a mobile phone with your hand while driving in WA is:",
     "options": ["Allowed at low speeds", "Allowed only for calls",
                 "Illegal for all drivers", "Allowed when stationary in traffic"],
     "correct": 2, "explanation": "Holding or touching a phone is illegal for all WA drivers. Use a fully hands-free system."},
    {"topic": "Road Trains", "difficulty": "medium", "state": "WA",
     "question": "When overtaking a road train on a remote WA highway you should:",
     "options": ["Overtake quickly without indicating", "Allow extra distance, signal clearly and only overtake on a long straight with clear visibility",
                 "Tailgate to use the slipstream", "Overtake on the shoulder"],
     "correct": 1, "explanation": "Road trains are very long — only overtake with a long clear straight and full visibility."},
    {"topic": "Wildlife", "difficulty": "easy", "state": "WA",
     "question": "Driving on country WA roads at dusk increases the risk of:",
     "options": ["Heavy congestion", "Sun glare only",
                 "Collisions with kangaroos and other wildlife", "Frost"],
     "correct": 2, "explanation": "Wildlife such as kangaroos are most active at dawn and dusk — slow down and stay alert."},
    {"topic": "Roundabouts", "difficulty": "medium", "state": "WA",
     "question": "When exiting a roundabout you should signal:",
     "options": ["Right", "Left just before your exit",
                 "Not at all if going straight", "Hazard lights"],
     "correct": 1, "explanation": "Always signal left as you approach your exit, regardless of direction."},
    {"topic": "Demerit Points", "difficulty": "medium", "state": "WA",
     "question": "L and P drivers in WA can lose their licence after accumulating:",
     "options": ["1 demerit point", "4 demerit points",
                 "12 demerit points", "20 demerit points"],
     "correct": 1, "explanation": "Novice drivers in WA face suspension at 4 demerit points within the qualifying period."},
    {"topic": "Pedestrians", "difficulty": "easy", "state": "WA",
     "question": "At a marked pedestrian crossing with people waiting to cross, you must:",
     "options": ["Continue at speed", "Stop and give way to pedestrians",
                 "Honk to warn them", "Wave them on while still moving"],
     "correct": 1, "explanation": "Stop and give way to pedestrians at any marked pedestrian crossing."},
    {"topic": "Towing", "difficulty": "medium", "state": "WA",
     "question": "When towing a caravan on a WA highway with a 110 km/h speed limit, you should:",
     "options": ["Drive at 110 km/h regardless",
                 "Drive at the lower of the posted limit or the vehicle/trailer rating, usually 100 km/h",
                 "Drive at 130 km/h to overtake quickly",
                 "Use the shoulder"],
     "correct": 1, "explanation": "Most towing combinations are limited to 100 km/h on Australian highways."},
    {"topic": "Headlights", "difficulty": "easy", "state": "WA",
     "question": "High-beam headlights must be dipped to low-beam:",
     "options": ["Only when oncoming vehicles are within 50 m, or when following within 200 m",
                 "Never", "Only on freeways",
                 "Only at intersections"],
     "correct": 0, "explanation": "Dip high beams to avoid dazzling drivers ahead (within 200 m) or oncoming (within 200 m / approximately 50 m practical)."},
]

DKT_SA_QUESTIONS = [
    {"topic": "Speed Limits", "difficulty": "easy", "state": "SA",
     "question": "The default urban speed limit in South Australia (unless signed) is:",
     "options": ["40 km/h", "50 km/h", "60 km/h", "70 km/h"],
     "correct": 1, "explanation": "50 km/h is the default built-up area limit in SA."},
    {"topic": "Mobile Phones", "difficulty": "easy", "state": "SA",
     "question": "A learner driver in SA may use a mobile phone:",
     "options": ["Hands-free for calls only", "For navigation only",
                 "Not at all while driving", "Only when stopped at lights"],
     "correct": 2, "explanation": "Learners and P1 drivers in SA must not use a mobile phone at all while driving."},
    {"topic": "School Zones", "difficulty": "easy", "state": "SA",
     "question": "The typical school zone speed limit in SA during posted hours is:",
     "options": ["25 km/h", "40 km/h", "60 km/h", "80 km/h"],
     "correct": 1, "explanation": "Most SA school zones are 25 km/h when children are present near schools and 40 km/h in many areas; follow signage."},
    {"topic": "Alcohol & Drugs", "difficulty": "easy", "state": "SA",
     "question": "The BAC limit for a learner driver in SA is:",
     "options": ["0.00%", "0.02%", "0.05%", "0.08%"],
     "correct": 0, "explanation": "L and P drivers in SA must have zero alcohol in their blood."},
    {"topic": "Right of Way", "difficulty": "medium", "state": "SA",
     "question": "At a T-intersection without signs or signals, the driver on the terminating road must:",
     "options": ["Continue without stopping", "Give way to all vehicles on the continuing road",
                 "Give way only to vehicles from the right", "Sound the horn"],
     "correct": 1, "explanation": "Vehicles on the terminating road of a T-intersection give way to all vehicles on the continuing road."},
    {"topic": "Roundabouts", "difficulty": "medium", "state": "SA",
     "question": "When entering a roundabout you must give way to:",
     "options": ["Larger vehicles", "Vehicles already in the roundabout",
                 "Vehicles approaching from your left", "Pedestrians on the footpath"],
     "correct": 1, "explanation": "Always give way to vehicles already in a roundabout."},
    {"topic": "Pedestrians", "difficulty": "easy", "state": "SA",
     "question": "At a koala crossing (children’s crossing) with flags out, drivers must:",
     "options": ["Continue at the posted speed",
                 "Stop and give way to all pedestrians until the crossing is clear",
                 "Slow but continue", "Sound the horn"],
     "correct": 1, "explanation": "Where flags are out, drivers must stop and give way until pedestrians have fully crossed."},
    {"topic": "Cyclists", "difficulty": "medium", "state": "SA",
     "question": "When overtaking a cyclist on a road with a limit of 60 km/h or less in SA you must allow:",
     "options": ["50 cm", "1 metre", "1.5 metres", "2 metres"],
     "correct": 1, "explanation": "At least 1 m minimum on roads up to 60 km/h, 1.5 m on faster roads."},
    {"topic": "Emergency Vehicles", "difficulty": "easy", "state": "SA",
     "question": "When you approach a stationary emergency vehicle with flashing lights, you must slow to:",
     "options": ["Maintain your speed", "Less than 25 km/h",
                 "60 km/h", "Stop immediately"],
     "correct": 1, "explanation": "In SA you must slow to 25 km/h or less when passing a stationary emergency vehicle displaying lights."},
    {"topic": "Headlights", "difficulty": "easy", "state": "SA",
     "question": "Headlights must be turned on between sunset and sunrise and whenever:",
     "options": ["A friend tells you to", "Visibility is reduced (rain, fog, dust)",
                 "Only on freeways", "The radio asks"],
     "correct": 1, "explanation": "Use headlights from sunset to sunrise and any time visibility is impaired."},
]

DKT_ACT_QUESTIONS = [
    {"topic": "Speed Limits", "difficulty": "easy", "state": "ACT",
     "question": "The default speed limit in ACT built-up areas (unless signed) is:",
     "options": ["40 km/h", "50 km/h", "60 km/h", "70 km/h"],
     "correct": 1, "explanation": "50 km/h is the default urban speed limit in the ACT."},
    {"topic": "Mobile Phones", "difficulty": "easy", "state": "ACT",
     "question": "An ACT learner driver may use a mobile phone:",
     "options": ["Hands-free only", "Not at all while driving",
                 "For navigation only", "Only on weekends"],
     "correct": 1, "explanation": "ACT learner and probationary drivers must not use a mobile phone at all while driving."},
    {"topic": "Light Rail", "difficulty": "medium", "state": "ACT",
     "question": "When approaching a light-rail crossing in Canberra you must:",
     "options": ["Speed up to cross quickly",
                 "Give way to light-rail vehicles and obey signals and signs",
                 "Stop only if you see a train", "Sound the horn"],
     "correct": 1, "explanation": "Obey the lights and signs at light-rail crossings and give way to trams."},
    {"topic": "Roundabouts", "difficulty": "medium", "state": "ACT",
     "question": "When using a roundabout in the ACT, you should signal:",
     "options": ["Only on entry", "Only on exit",
                 "Both as required: right or left on entry and left when exiting",
                 "Not at all"],
     "correct": 2, "explanation": "Signal right when turning right, left when turning left, and always signal left as you exit."},
    {"topic": "Alcohol & Drugs", "difficulty": "easy", "state": "ACT",
     "question": "The BAC limit for a fully licensed driver in the ACT is below:",
     "options": ["0.00%", "0.02%", "0.05%", "0.08%"],
     "correct": 2, "explanation": "Open-licence drivers in the ACT must remain below 0.05% BAC."},
    {"topic": "Pedestrians", "difficulty": "easy", "state": "ACT",
     "question": "At a marked pedestrian crossing in Canberra, you must:",
     "options": ["Continue at normal speed", "Stop and give way to pedestrians",
                 "Sound your horn", "Speed up to clear the area"],
     "correct": 1, "explanation": "Stop and give way to pedestrians at any marked pedestrian crossing."},
    {"topic": "Parking", "difficulty": "easy", "state": "ACT",
     "question": "You must not park within how many metres of an intersection without traffic lights in the ACT?",
     "options": ["3 metres", "5 metres", "10 metres", "20 metres"],
     "correct": 2, "explanation": "Parking is prohibited within 10 m of an intersection without traffic lights."},
    {"topic": "School Zones", "difficulty": "easy", "state": "ACT",
     "question": "ACT school zones generally operate at:",
     "options": ["20 km/h", "30 km/h", "40 km/h", "60 km/h"],
     "correct": 2, "explanation": "Most ACT school zones are 40 km/h during posted school times."},
    {"topic": "Cyclists", "difficulty": "medium", "state": "ACT",
     "question": "In the ACT, cyclists are legally entitled to:",
     "options": ["Use any motorway", "Use bike lanes and shared paths and to ride two abreast on most roads",
                 "Ride only on footpaths", "Ride only in parks"],
     "correct": 1, "explanation": "Cyclists may use roads, bike lanes and most shared paths and may ride two abreast within rules."},
    {"topic": "Demerit Points", "difficulty": "medium", "state": "ACT",
     "question": "ACT learner and provisional drivers may lose their licence after accumulating:",
     "options": ["1 demerit point", "4 demerit points",
                 "12 demerit points", "20 demerit points"],
     "correct": 1, "explanation": "ACT novice drivers face suspension at 4 demerit points within the qualifying period."},
]

DKT_TAS_QUESTIONS = [
    {"topic": "Speed Limits", "difficulty": "easy", "state": "TAS",
     "question": "The default urban speed limit in Tasmania (unless signed) is:",
     "options": ["40 km/h", "50 km/h", "60 km/h", "70 km/h"],
     "correct": 1, "explanation": "50 km/h is the default built-up area speed limit in Tasmania."},
    {"topic": "Wildlife", "difficulty": "easy", "state": "TAS",
     "question": "Driving Tasmanian rural roads at dusk and dawn requires extra care for:",
     "options": ["Heavy traffic", "Snowy conditions year-round",
                 "Wildlife such as wombats, wallabies and Tasmanian devils",
                 "Vehicle ferries"],
     "correct": 2, "explanation": "Tasmania has abundant wildlife and many strikes happen at dawn and dusk. Reduce speed and be alert."},
    {"topic": "Alcohol & Drugs", "difficulty": "easy", "state": "TAS",
     "question": "TAS learner and provisional drivers must have a BAC of:",
     "options": ["0.00%", "0.02%", "0.05%", "0.08%"],
     "correct": 0, "explanation": "Novice drivers in Tasmania must have zero alcohol in their blood."},
    {"topic": "Mobile Phones", "difficulty": "easy", "state": "TAS",
     "question": "Open-licence drivers in TAS may use a mobile phone:",
     "options": ["Hand-held for calls only",
                 "Only in a hands-free or properly mounted system for calls and audio",
                 "Freely for texting",
                 "Only when stopped at lights"],
     "correct": 1, "explanation": "Open-licence drivers must use hands-free or a mounted device — never handheld."},
    {"topic": "Wet Weather", "difficulty": "medium", "state": "TAS",
     "question": "On a wet TAS road you should:",
     "options": ["Drive at the normal posted limit", "Reduce speed and increase following distance",
                 "Tailgate to maintain warmth", "Use hazard lights and continue"],
     "correct": 1, "explanation": "Wet conditions reduce traction and double braking distance — slow down and leave a bigger gap."},
    {"topic": "Roundabouts", "difficulty": "medium", "state": "TAS",
     "question": "Entering a roundabout, you must give way to:",
     "options": ["All vehicles already on the roundabout", "Only larger vehicles",
                 "Vehicles approaching from the left only", "No vehicles — you have right of way"],
     "correct": 0, "explanation": "Give way to all vehicles already in the roundabout."},
    {"topic": "Emergency Vehicles", "difficulty": "easy", "state": "TAS",
     "question": "When a TAS emergency vehicle is stationary with lights flashing, you must:",
     "options": ["Drive past at the posted speed", "Slow to 40 km/h or as signed and give the vehicle space",
                 "Sound your horn", "Stop and reverse"],
     "correct": 1, "explanation": "Slow to 40 km/h (or signed limit) when passing stationary emergency vehicles in TAS."},
    {"topic": "Headlights", "difficulty": "easy", "state": "TAS",
     "question": "Headlights must be on in Tasmania when:",
     "options": ["Only on freeways", "Between sunset and sunrise and when visibility is reduced",
                 "Only in summer", "Whenever you feel like it"],
     "correct": 1, "explanation": "Use headlights from sunset to sunrise and whenever visibility is poor (fog, rain, dust)."},
    {"topic": "Pedestrians", "difficulty": "easy", "state": "TAS",
     "question": "At a school crossing with the supervisor’s STOP sign held up, drivers must:",
     "options": ["Continue cautiously", "Stop and remain stopped until the sign is lowered",
                 "Sound their horn", "Drive around the supervisor"],
     "correct": 1, "explanation": "Stop and remain stopped until the supervisor lowers the sign and the crossing is clear."},
    {"topic": "Demerit Points", "difficulty": "medium", "state": "TAS",
     "question": "L and P drivers in Tasmania may face suspension after accumulating:",
     "options": ["3 demerit points", "5 demerit points",
                 "8 demerit points", "13 demerit points"],
     "correct": 1, "explanation": "Novice drivers in TAS face suspension when they reach 5 or more demerit points."},
]

DKT_NT_QUESTIONS = [
    {"topic": "Speed Limits", "difficulty": "easy", "state": "NT",
     "question": "The default speed limit in NT built-up areas (unless signed) is:",
     "options": ["40 km/h", "50 km/h", "60 km/h", "80 km/h"],
     "correct": 1, "explanation": "50 km/h is the default urban speed limit in the Northern Territory."},
    {"topic": "Highway Driving", "difficulty": "medium", "state": "NT",
     "question": "On many NT open highways, the default rural speed limit (unless signed) is:",
     "options": ["80 km/h", "100 km/h", "110 km/h", "130 km/h"],
     "correct": 2, "explanation": "The NT default rural limit is 110 km/h, with some sections signed to 130 km/h."},
    {"topic": "Road Trains", "difficulty": "medium", "state": "NT",
     "question": "When approaching a road train you should:",
     "options": ["Overtake on the shoulder", "Maintain extra distance, allow a long clear straight before overtaking, and never overtake on a crest",
                 "Tailgate to draft", "Sound your horn to pass"],
     "correct": 1, "explanation": "Road trains are extremely long. Plan overtakes carefully and only on clear straights."},
    {"topic": "Wildlife", "difficulty": "easy", "state": "NT",
     "question": "Driving NT rural roads at night significantly increases the risk of:",
     "options": ["Heavy congestion", "Wildlife strikes with kangaroos, cattle and buffalo",
                 "Snowfall", "Cycle traffic"],
     "correct": 1, "explanation": "Wildlife and stray livestock are common on NT roads, especially at night. Slow down and stay alert."},
    {"topic": "Alcohol & Drugs", "difficulty": "easy", "state": "NT",
     "question": "L and P drivers in NT must have a BAC of:",
     "options": ["0.00%", "0.02%", "0.05%", "0.08%"],
     "correct": 0, "explanation": "Learner and provisional drivers in the NT must have zero alcohol in their blood."},
    {"topic": "Mobile Phones", "difficulty": "easy", "state": "NT",
     "question": "Holding a mobile phone while driving in the NT is:",
     "options": ["Permitted for short calls", "Permitted for navigation",
                 "Illegal — only fully hands-free use is allowed", "Permitted on highways"],
     "correct": 2, "explanation": "Holding a phone while driving is illegal in the NT — use hands-free only."},
    {"topic": "Fatigue", "difficulty": "easy", "state": "NT",
     "question": "On long NT highway trips, the best way to manage fatigue is to:",
     "options": ["Drink a strong coffee", "Take a 15–20 minute power nap and share driving",
                 "Open the windows", "Listen to loud music"],
     "correct": 1, "explanation": "Short power naps are the most effective short-term remedy; share driving where possible."},
    {"topic": "Roundabouts", "difficulty": "medium", "state": "NT",
     "question": "Entering a roundabout, you must give way to:",
     "options": ["Vehicles already in the roundabout", "Vehicles from the left only",
                 "Larger vehicles only", "No one"],
     "correct": 0, "explanation": "Give way to all vehicles already on the roundabout."},
    {"topic": "Emergency Vehicles", "difficulty": "easy", "state": "NT",
     "question": "When an emergency vehicle approaches you on a single-lane NT highway, you should:",
     "options": ["Continue at the same speed", "Pull off onto a safe shoulder when possible to let it pass",
                 "Sound your horn", "Stop in the middle of the lane"],
     "correct": 1, "explanation": "Where safe, move to the shoulder to let the emergency vehicle pass."},
    {"topic": "Demerit Points", "difficulty": "medium", "state": "NT",
     "question": "NT L and P drivers may face suspension after accumulating:",
     "options": ["3 demerit points", "5 demerit points",
                 "8 demerit points", "13 demerit points"],
     "correct": 1, "explanation": "Novice drivers in NT face suspension when they accumulate 5 or more demerit points."},
]


# ====================================================================
# Work-licence categories (national, paraphrased)
# ====================================================================

WHITE_CARD_QUESTIONS = [
    {"topic": "Site Induction", "difficulty": "easy",
     "question": "A construction site induction is required to:",
     "options": ["Promote the company brand",
                 "Provide site-specific safety information before work begins",
                 "Replace formal training", "Test workers’ general knowledge"],
     "correct": 1, "explanation": "Site inductions explain the specific hazards, rules and emergency procedures of that site."},
    {"topic": "PPE", "difficulty": "easy",
     "question": "The minimum PPE typically required on a construction site is:",
     "options": ["Sunglasses only",
                 "High-visibility clothing, hard hat, safety footwear and safety eyewear as required",
                 "Closed-toe sandals", "A T-shirt and shorts"],
     "correct": 1, "explanation": "Hi-vis, hard hat and steel-capped boots are the baseline PPE on most Australian sites."},
    {"topic": "Hazard ID", "difficulty": "easy",
     "question": "The first step in the hazard management process is to:",
     "options": ["Eliminate the hazard", "Identify the hazard",
                 "Use PPE", "Ignore minor risks"],
     "correct": 1, "explanation": "You must first identify hazards before assessing and controlling them."},
    {"topic": "Hierarchy of Controls", "difficulty": "medium",
     "question": "The most effective level of control in the hierarchy of controls is:",
     "options": ["Personal protective equipment", "Administrative controls",
                 "Elimination of the hazard", "Warning signs"],
     "correct": 2, "explanation": "Elimination — removing the hazard entirely — is the most effective control."},
    {"topic": "Working at Heights", "difficulty": "medium",
     "question": "When working at height above 2 metres, you should:",
     "options": ["Work alone for speed", "Use fall-protection systems such as guardrails, harnesses or scaffolding",
                 "Avoid wearing PPE", "Only work in dry weather"],
     "correct": 1, "explanation": "Falls from heights are a major cause of construction deaths. Always use approved fall protection."},
    {"topic": "Manual Handling", "difficulty": "easy",
     "question": "When lifting a heavy object you should:",
     "options": ["Bend at the waist with straight legs",
                 "Use your legs, keep the load close to your body and avoid twisting",
                 "Lift quickly", "Hold your breath"],
     "correct": 1, "explanation": "Use legs not back, keep load close, avoid twisting — to reduce risk of injury."},
    {"topic": "Incident Reporting", "difficulty": "easy",
     "question": "If you witness an incident or near miss on site, you should:",
     "options": ["Ignore it if no one was hurt", "Report it to your supervisor as soon as possible",
                 "Wait for end of shift", "Tell only co-workers"],
     "correct": 1, "explanation": "Report incidents and near misses promptly so hazards can be controlled before harm occurs."},
    {"topic": "Electrical Safety", "difficulty": "medium",
     "question": "Damaged power tools or extension leads on site must be:",
     "options": ["Used until they fail completely",
                 "Tagged out of service and reported, never used",
                 "Patched with electrical tape", "Used only on weekends"],
     "correct": 1, "explanation": "Damaged electrical equipment must be removed from service immediately and tagged."},
    {"topic": "Drugs & Alcohol", "difficulty": "easy",
     "question": "Working under the influence of drugs or alcohol on a construction site is:",
     "options": ["Allowed during breaks", "Strictly prohibited and unsafe",
                 "OK if you are experienced", "OK after lunch"],
     "correct": 1, "explanation": "Drugs and alcohol impair judgement and reaction — strictly prohibited on site."},
    {"topic": "Emergency Procedures", "difficulty": "easy",
     "question": "If a fire alarm sounds on site, you should:",
     "options": ["Finish your task first", "Evacuate by the marked routes to the assembly point",
                 "Hide under a desk", "Continue working"],
     "correct": 1, "explanation": "Always evacuate via marked routes and assemble at the designated point for a head count."},
]

RCG_QUESTIONS = [
    {"topic": "Responsible Gambling", "difficulty": "easy",
     "question": "Responsible Conduct of Gambling (RCG) training aims to:",
     "options": ["Encourage more gambling spend",
                 "Minimise harm by ensuring gambling is conducted responsibly and lawfully",
                 "Train dealers to be entertainers", "Promote alcohol sales"],
     "correct": 1, "explanation": "RCG focuses on minimising gambling-related harm and complying with the law."},
    {"topic": "Signs of Problem Gambling", "difficulty": "medium",
     "question": "Which of the following is a warning sign of problem gambling?",
     "options": ["Playing for a short time and leaving",
                 "Chasing losses with increasing bets, distressed behaviour, asking for credit",
                 "Buying a sensible drink", "Bringing a friend"],
     "correct": 1, "explanation": "Chasing losses, distress and seeking credit are common indicators of problem gambling."},
    {"topic": "Self-Exclusion", "difficulty": "easy",
     "question": "A self-exclusion program allows a person to:",
     "options": ["Be banned by police forever",
                 "Voluntarily ban themselves from gambling at the venue or operator",
                 "Earn loyalty points", "Get free drinks"],
     "correct": 1, "explanation": "Self-exclusion lets patrons voluntarily exclude themselves from gambling environments."},
    {"topic": "Minors", "difficulty": "easy",
     "question": "Allowing a minor to gamble or remain in a gaming area is:",
     "options": ["Acceptable with parental permission", "A serious offence under gambling laws",
                 "Allowed during lunch hours", "Only an issue at night"],
     "correct": 1, "explanation": "Minors must not gamble or be in gaming areas. Violations carry significant penalties."},
    {"topic": "Cash & Credit", "difficulty": "medium",
     "question": "Lending money or extending credit to a patron for gambling is:",
     "options": ["Encouraged for loyal customers", "Strictly prohibited at licensed venues",
                 "OK in small amounts", "Required by RCG"],
     "correct": 1, "explanation": "Providing credit or lending money for gambling at a venue is generally prohibited."},
    {"topic": "Advertising", "difficulty": "medium",
     "question": "Gambling advertising must:",
     "options": ["Promise wins", "Be truthful and not target minors or vulnerable people",
                 "Suggest gambling solves financial problems", "Make light of losses"],
     "correct": 1, "explanation": "Advertising must be honest, must not target minors and must not promote gambling as a solution to problems."},
    {"topic": "Intoxicated Patrons", "difficulty": "easy",
     "question": "An intoxicated patron attempting to gamble should be:",
     "options": ["Served as usual", "Politely refused service and offered support information",
                 "Given larger bets", "Encouraged to keep playing"],
     "correct": 1, "explanation": "Refuse gambling service to intoxicated patrons; offer help information where appropriate."},
    {"topic": "Counselling Referrals", "difficulty": "easy",
     "question": "Gambling counselling support information must be:",
     "options": ["Hidden from view", "Displayed prominently and offered when needed",
                 "Only given on request from police", "Posted only online"],
     "correct": 1, "explanation": "Venues must display counselling and help-line information for patrons."},
    {"topic": "Cooling-Off & Limits", "difficulty": "medium",
     "question": "Pre-commitment systems allow players to:",
     "options": ["Bet more than they can afford",
                 "Set limits on time and money spent on gambling activities",
                 "Get loans from the venue", "Skip RCG rules"],
     "correct": 1, "explanation": "Pre-commitment empowers patrons to set spending and time limits in advance."},
    {"topic": "Incident Reporting", "difficulty": "easy",
     "question": "If a patron shows signs of distress related to gambling, staff should:",
     "options": ["Encourage them to keep playing", "Approach respectfully, offer help info and notify the supervisor",
                 "Ignore them", "Photograph them"],
     "correct": 1, "explanation": "Approach the patron with care, offer support information and escalate to the supervisor or counsellor."},
]

SECURITY_QUESTIONS = [
    {"topic": "Role of Security", "difficulty": "easy",
     "question": "A security officer’s primary role is to:",
     "options": ["Make arrests like police",
                 "Observe, report and act within their lawful authority to keep people and property safe",
                 "Provide medical surgery", "Drive emergency vehicles"],
     "correct": 1, "explanation": "Security officers protect people and property through observation, reporting and lawful action."},
    {"topic": "Use of Force", "difficulty": "medium",
     "question": "Use of force by a security officer must always be:",
     "options": ["Maximum at all times",
                 "The minimum reasonably necessary and proportionate to the threat",
                 "Whatever the officer feels", "Encouraged for compliance"],
     "correct": 1, "explanation": "Force must be reasonable, proportionate and only the minimum needed to control the situation."},
    {"topic": "Conflict Resolution", "difficulty": "medium",
     "question": "The first preferred response to an aggressive patron is to:",
     "options": ["Physically restrain immediately", "Use calm verbal de-escalation techniques",
                 "Pepper spray them", "Threaten them"],
     "correct": 1, "explanation": "Verbal de-escalation should always be attempted first to defuse conflict safely."},
    {"topic": "Citizen’s Arrest", "difficulty": "medium",
     "question": "A lawful citizen’s arrest by a security officer in Australia requires that the person:",
     "options": ["Looks suspicious",
                 "Is found committing an indictable offence (or as otherwise allowed by law) and is handed to police as soon as possible",
                 "Is wearing dark clothes", "Refuses to give their name"],
     "correct": 1, "explanation": "Citizen’s arrest powers are limited — usually requires the person to be found committing an indictable offence and police must be involved promptly."},
    {"topic": "Reporting", "difficulty": "easy",
     "question": "Security incident reports should be:",
     "options": ["Verbal only", "Accurate, factual, written and signed at the time",
                 "Filed once a month", "Written from rumour"],
     "correct": 1, "explanation": "Reports must be factual, accurate, contemporaneous and signed for legal value."},
    {"topic": "WHS", "difficulty": "easy",
     "question": "Personal safety equipment for security officers may include:",
     "options": ["Body armour only",
                 "Appropriate uniform, communications device, torch, body cam (if authorised) and any approved restraints",
                 "Their own knife", "Random items"],
     "correct": 1, "explanation": "Security PPE varies by role but always includes communications and only approved restraints / equipment."},
    {"topic": "Discrimination", "difficulty": "easy",
     "question": "Refusing entry on the basis of race, religion or gender alone is:",
     "options": ["Permitted", "Unlawful under anti-discrimination law",
                 "Optional", "Recommended"],
     "correct": 1, "explanation": "Refusal must be based on lawful reasons such as house policy or safety — not protected attributes."},
    {"topic": "Evidence Handling", "difficulty": "medium",
     "question": "When a security officer takes possession of evidence, they must:",
     "options": ["Keep it permanently",
                 "Record details and hand it to police or store securely per procedure",
                 "Show it to friends", "Post it on social media"],
     "correct": 1, "explanation": "Maintain chain of custody and hand evidence to police or secure storage following procedure."},
    {"topic": "Emergency Response", "difficulty": "easy",
     "question": "If a fire breaks out at a venue, the security officer should:",
     "options": ["Continue patrols as usual",
                 "Activate the alarm, assist evacuation, contact emergency services and follow the site plan",
                 "Hide the alarm", "Wait for guests to notice"],
     "correct": 1, "explanation": "Follow the venue’s emergency plan: alarm, evacuate, call emergency services, account for people."},
    {"topic": "Code of Conduct", "difficulty": "easy",
     "question": "Accepting a cash bribe from a patron to look the other way is:",
     "options": ["A perk of the job", "Serious misconduct and potentially criminal",
                 "Allowed if small", "Encouraged"],
     "correct": 1, "explanation": "Bribery is a serious offence that breaches industry codes and the law."},
]

FORKLIFT_QUESTIONS = [
    {"topic": "Licensing", "difficulty": "easy",
     "question": "In Australia, operating a powered forklift truck (LF) requires:",
     "options": ["No formal licence",
                 "A valid High Risk Work Licence (HRWL) appropriate to the class",
                 "A car licence only", "A first-aid certificate only"],
     "correct": 1, "explanation": "Forklift operators must hold an LF (or LO for order pickers) High Risk Work Licence."},
    {"topic": "Pre-Start Checks", "difficulty": "easy",
     "question": "Before operating a forklift you must:",
     "options": ["Just turn the key and start work",
                 "Conduct a pre-start inspection including tyres, brakes, horn, hydraulics and safety devices",
                 "Skip checks if you used it yesterday", "Check fuel only"],
     "correct": 1, "explanation": "Documented daily pre-start checks are required to confirm the forklift is safe to operate."},
    {"topic": "Load Capacity", "difficulty": "medium",
     "question": "The forklift’s rated load capacity is shown on the:",
     "options": ["Wheel", "Data plate (compliance plate)",
                 "Mast", "Wherever the operator decides"],
     "correct": 1, "explanation": "The data/compliance plate lists the rated capacity at a specified load centre."},
    {"topic": "Travel & Visibility", "difficulty": "medium",
     "question": "When travelling without a load and visibility is restricted by the mast, you should:",
     "options": ["Continue forward and look sideways",
                 "Travel in reverse where safe, with a clear view, or use a spotter",
                 "Lift the forks high to see", "Drive faster"],
     "correct": 1, "explanation": "If forward visibility is blocked, travel in reverse where safe or use a spotter."},
    {"topic": "Stability", "difficulty": "medium",
     "question": "To maintain forklift stability you should:",
     "options": ["Travel with the forks raised high",
                 "Keep the load low (about 100–150 mm above the ground) and tilted back while travelling",
                 "Take sharp corners at speed", "Ignore the stability triangle"],
     "correct": 1, "explanation": "Travel with the load low and tilted back to keep the centre of gravity within the stability triangle."},
    {"topic": "Pedestrians", "difficulty": "easy",
     "question": "When pedestrians are nearby you must:",
     "options": ["Ignore them", "Slow down, sound the horn at intersections, give way and use eye contact",
                 "Speed past quickly", "Wave them out of the way"],
     "correct": 1, "explanation": "Pedestrians always have right of way. Slow, signal and give way."},
    {"topic": "Refuelling", "difficulty": "medium",
     "question": "When refuelling or recharging a forklift you should:",
     "options": ["Smoke while refuelling",
                 "Follow the manufacturer’s procedure in a designated, ventilated area with the engine off",
                 "Do it indoors with no ventilation", "Refuel while loading a pallet"],
     "correct": 1, "explanation": "Refuel/recharge only in designated ventilated areas with the engine off and no ignition sources."},
    {"topic": "Loads", "difficulty": "easy",
     "question": "A load is considered unstable when it:",
     "options": ["Is wrapped tightly and balanced",
                 "Is overhanging, leaning, damaged or exceeds the rated capacity",
                 "Sits on a sound pallet", "Is centred on the forks"],
     "correct": 1, "explanation": "Overhanging, damaged or overweight loads are unstable and unsafe to lift."},
    {"topic": "Emergency Procedure", "difficulty": "easy",
     "question": "If the forklift begins to tip over, you should:",
     "options": ["Jump clear", "Stay seated, brace against the steering wheel and lean away from the fall",
                 "Try to grab the load", "Stand on the seat"],
     "correct": 1, "explanation": "Stay in the cab, brace and lean away from the direction of the fall — jumping is far more dangerous."},
    {"topic": "Shutdown", "difficulty": "easy",
     "question": "When parking a forklift, you must:",
     "options": ["Leave the keys in for the next operator and forks raised",
                 "Lower the forks to the ground, apply the park brake, turn off the engine and remove the key",
                 "Block a walkway", "Leave the engine running"],
     "correct": 1, "explanation": "Forks down, park brake on, engine off, key out — always."},
]
