"""
Passaroo seed data — ORIGINAL, paraphrased practice questions.
NOT copied from official government exams. Independently written
around publicly known learning objectives.
"""

DKT_QUESTIONS = [
    {"topic": "Speed Limits", "difficulty": "easy", "state": "NSW",
     "question": "In a built-up residential area in NSW, unless otherwise signed, the default speed limit is:",
     "options": ["40 km/h", "50 km/h", "60 km/h", "80 km/h"],
     "correct": 1, "explanation": "In NSW, the default urban speed limit in built-up areas is 50 km/h unless signs say otherwise."},
    {"topic": "Speed Limits", "difficulty": "easy", "state": "NSW",
     "question": "When passing a stationary school bus that has its red lights flashing, the maximum speed is:",
     "options": ["10 km/h", "25 km/h", "40 km/h", "60 km/h"],
     "correct": 2, "explanation": "When a school bus is stopped and flashing red lights, you must not exceed 40 km/h to protect children."},
    {"topic": "Alcohol & Drugs", "difficulty": "easy", "state": "NSW",
     "question": "A fully licensed driver in Australia must have a blood alcohol concentration below:",
     "options": ["0.00%", "0.02%", "0.05%", "0.08%"],
     "correct": 2, "explanation": "Full licence holders must keep BAC under 0.05%. Learner and provisional drivers must remain at 0.00%."},
    {"topic": "Alcohol & Drugs", "difficulty": "medium", "state": "NSW",
     "question": "For learner and P1 drivers, the legal blood alcohol limit is:",
     "options": ["0.00%", "0.02%", "0.05%", "No limit"],
     "correct": 0, "explanation": "Learner, P1 and P2 drivers must have zero alcohol in their blood while driving."},
    {"topic": "Road Signs", "difficulty": "easy", "state": "NSW",
     "question": "A red octagonal sign with the word STOP requires you to:",
     "options": ["Slow down and proceed if clear", "Stop completely behind the line then proceed when safe",
                 "Give way only to vehicles on the right", "Stop only if other vehicles are present"],
     "correct": 1, "explanation": "STOP signs require a full stop behind the line. Proceed only when it is safe to do so."},
    {"topic": "Road Signs", "difficulty": "easy", "state": "NSW",
     "question": "A triangular sign with a red border pointing downward means:",
     "options": ["Stop", "Give Way", "No Entry", "Warning"],
     "correct": 1, "explanation": "An inverted red-bordered triangle is the Give Way sign. Slow down and give way to other traffic."},
    {"topic": "Intersections", "difficulty": "medium", "state": "NSW",
     "question": "At an uncontrolled intersection without signs or signals, you must give way to:",
     "options": ["Vehicles coming from your left", "Vehicles coming from your right",
                 "The larger vehicle", "Whoever arrived first"],
     "correct": 1, "explanation": "At an uncontrolled intersection, you give way to vehicles approaching from your right."},
    {"topic": "Intersections", "difficulty": "medium", "state": "NSW",
     "question": "When turning right at traffic lights with a green light (no arrow), you must:",
     "options": ["Turn immediately", "Give way to oncoming traffic going straight or turning left",
                 "Wait for a green arrow", "Sound your horn"],
     "correct": 1, "explanation": "A green light (no arrow) allows turning right only after giving way to oncoming traffic."},
    {"topic": "Overtaking", "difficulty": "medium", "state": "NSW",
     "question": "You may cross a single unbroken (solid) white centre line to overtake when:",
     "options": ["You are running late", "Never — solid lines must not be crossed to overtake",
                 "The vehicle ahead is travelling under 40 km/h", "Visibility is clear for 100 m"],
     "correct": 1, "explanation": "Solid centre lines indicate it is unsafe to overtake. You must not cross them to overtake."},
    {"topic": "Parking", "difficulty": "easy", "state": "NSW",
     "question": "You must not park within how many metres of an intersection without traffic lights?",
     "options": ["3 metres", "5 metres", "10 metres", "20 metres"],
     "correct": 2, "explanation": "Parking is prohibited within 10 m of an intersection without traffic lights to keep sightlines clear."},
    {"topic": "Parking", "difficulty": "easy", "state": "NSW",
     "question": "You must not stop within how many metres of a pedestrian crossing?",
     "options": ["5 metres", "10 metres", "20 metres", "50 metres"],
     "correct": 1, "explanation": "Stopping within 10 m before a pedestrian crossing is not allowed for safety reasons."},
    {"topic": "Seatbelts & Safety", "difficulty": "easy", "state": "NSW",
     "question": "Children under 7 years of age must be restrained in:",
     "options": ["The front seat with an adult seatbelt", "An approved child restraint suitable for their age and size",
                 "Any seat with a lap belt", "The boot is acceptable for short trips"],
     "correct": 1, "explanation": "Children under 7 must use an age-appropriate approved child restraint."},
    {"topic": "Headlights", "difficulty": "easy", "state": "NSW",
     "question": "Headlights must be turned on:",
     "options": ["Only after sunset", "Between sunset and sunrise, and any time visibility is reduced",
                 "Only in heavy rain", "Only when other vehicles approach"],
     "correct": 1, "explanation": "Use headlights between sunset and sunrise and any time visibility drops (fog, heavy rain, etc.)."},
    {"topic": "Mobile Phones", "difficulty": "easy", "state": "NSW",
     "question": "While driving, a learner driver may use a mobile phone:",
     "options": ["For navigation only", "In hands-free mode", "Only when stopped at lights",
                 "Not at all, including hands-free"],
     "correct": 3, "explanation": "Learner and P1 drivers must not use a mobile phone at all while driving, including hands-free."},
    {"topic": "Roundabouts", "difficulty": "medium", "state": "NSW",
     "question": "When entering a roundabout, you must give way to:",
     "options": ["Vehicles entering from your left", "Vehicles already in the roundabout",
                 "Larger vehicles only", "No one — you have right of way"],
     "correct": 1, "explanation": "Always give way to traffic already in the roundabout before entering."},
    {"topic": "Roundabouts", "difficulty": "medium", "state": "NSW",
     "question": "When exiting a roundabout, you should indicate:",
     "options": ["Right", "Left as you pass the exit before yours",
                 "Not at all", "Hazard lights"],
     "correct": 1, "explanation": "Signal left just before the exit you intend to take, even when going straight or right."},
    {"topic": "Pedestrians", "difficulty": "easy", "state": "NSW",
     "question": "At a pedestrian crossing with people waiting to cross, you must:",
     "options": ["Continue at normal speed", "Stop and give way to pedestrians",
                 "Sound your horn", "Speed up to clear the area"],
     "correct": 1, "explanation": "Drivers must stop and give way to pedestrians at marked pedestrian crossings."},
    {"topic": "Emergency Vehicles", "difficulty": "easy", "state": "NSW",
     "question": "When you see an emergency vehicle with flashing lights and sirens behind you, you should:",
     "options": ["Speed up to get out of the way", "Pull over safely and let it pass",
                 "Slow down but stay in your lane", "Stop immediately in the middle of the road"],
     "correct": 1, "explanation": "Pull to the left when safe to do so and allow emergency vehicles to pass."},
    {"topic": "Following Distance", "difficulty": "medium", "state": "NSW",
     "question": "The recommended minimum following distance in good conditions is:",
     "options": ["1 second", "2 seconds", "3 seconds", "5 seconds"],
     "correct": 2, "explanation": "A 3-second gap gives you time to react and brake safely in good conditions."},
    {"topic": "Following Distance", "difficulty": "medium", "state": "NSW",
     "question": "In wet or slippery conditions, you should:",
     "options": ["Use the same following distance", "Halve your following distance",
                 "Double your following distance", "Drive closer to see better"],
     "correct": 2, "explanation": "Wet conditions double braking distance — double your following gap to stay safe."},
    {"topic": "Demerit Points", "difficulty": "medium", "state": "NSW",
     "question": "Learner drivers in NSW can accumulate a maximum of how many demerit points before suspension?",
     "options": ["2 points", "4 points", "7 points", "13 points"],
     "correct": 1, "explanation": "Learner and P1 drivers can accumulate up to 4 demerit points before licence suspension."},
    {"topic": "Fatigue", "difficulty": "easy", "state": "NSW",
     "question": "The most effective way to combat driver fatigue on a long trip is to:",
     "options": ["Drink a strong coffee", "Open the windows for fresh air",
                 "Take a power nap of 15–20 minutes", "Turn up the radio"],
     "correct": 2, "explanation": "Short naps refresh you most effectively. Caffeine and air only mask tiredness briefly."},
    {"topic": "Hand Signals", "difficulty": "easy", "state": "NSW",
     "question": "If your indicators fail, signalling a right turn with your arm means:",
     "options": ["Arm extended down", "Arm bent up at the elbow",
                 "Arm extended straight out the window", "Arm waving up and down"],
     "correct": 2, "explanation": "An arm extended straight out signals a right turn when indicators are not working."},
    {"topic": "School Zones", "difficulty": "easy", "state": "NSW",
     "question": "School zone speed limits in NSW typically apply:",
     "options": ["All day every day", "Only weekdays during designated school terms and hours",
                 "Only when children are visible", "Only on Mondays"],
     "correct": 1, "explanation": "School zone limits apply weekdays during school terms within the posted times (usually 8–9:30 and 2:30–4)."},
    {"topic": "Towing", "difficulty": "medium", "state": "NSW",
     "question": "When towing a trailer on a freeway, the maximum speed you can travel is generally:",
     "options": ["80 km/h", "90 km/h", "100 km/h", "110 km/h"],
     "correct": 2, "explanation": "Most vehicles towing trailers are limited to 100 km/h on Australian freeways."},
    {"topic": "Lane Changes", "difficulty": "easy", "state": "NSW",
     "question": "Before changing lanes, you must:",
     "options": ["Indicate only", "Check mirrors only",
                 "Indicate, check mirrors and blind spots, then move when safe", "Sound the horn"],
     "correct": 2, "explanation": "Always indicate, check mirrors and your blind spot, then merge when there is a safe gap."},
    {"topic": "Bicycle Riders", "difficulty": "medium", "state": "NSW",
     "question": "When passing a bicycle rider on a road with a speed limit of 60 km/h or less, you must leave at least:",
     "options": ["50 cm", "1 metre", "1.5 metres", "2 metres"],
     "correct": 1, "explanation": "In NSW, leave at least 1 m when passing cyclists where the limit is 60 km/h or less, 1.5 m above that."},
    {"topic": "Tyres", "difficulty": "easy", "state": "NSW",
     "question": "The minimum legal tyre tread depth for passenger vehicles is:",
     "options": ["1.0 mm", "1.5 mm", "2.0 mm", "3.0 mm"],
     "correct": 1, "explanation": "Tyres must have at least 1.5 mm of tread across the wearing surface to be roadworthy."},
    {"topic": "Reversing", "difficulty": "easy", "state": "NSW",
     "question": "When reversing, you must:",
     "options": ["Reverse for any distance needed", "Reverse only as far as is reasonable and safe",
                 "Always have a passenger guide you", "Never reverse on a public road"],
     "correct": 1, "explanation": "Reverse only as far as necessary and only when it is safe to do so."},
    {"topic": "Merging", "difficulty": "medium", "state": "NSW",
     "question": "When two lanes merge into one and there are no road markings, you must give way to:",
     "options": ["The vehicle on your left", "The vehicle on your right",
                 "Any vehicle ahead of you", "The faster vehicle"],
     "correct": 2, "explanation": "Zip-merge rule: give way to any vehicle whose front is ahead of yours."},
]

CITIZENSHIP_QUESTIONS = [
    {"topic": "Australian Values", "difficulty": "easy",
     "question": "Which of the following best describes a core Australian value?",
     "options": ["Respect for the equal worth, dignity and freedom of the individual",
                 "Strict religious adherence to one faith",
                 "Mandatory military service for all",
                 "Hereditary class systems"],
     "correct": 0, "explanation": "Respect for the equal worth, dignity and freedom of every person is a cornerstone Australian value."},
    {"topic": "Australian Values", "difficulty": "easy",
     "question": "In Australia, men and women are:",
     "options": ["Treated differently before the law", "Equal under the law",
                 "Separated in public services", "Required to share property equally"],
     "correct": 1, "explanation": "Equality of men and women is enshrined as a fundamental Australian value."},
    {"topic": "Government", "difficulty": "easy",
     "question": "Australia’s system of government is best described as:",
     "options": ["Absolute monarchy", "One-party state",
                 "Parliamentary democracy and a constitutional monarchy", "Direct democracy"],
     "correct": 2, "explanation": "Australia is a parliamentary democracy and a constitutional monarchy with the Sovereign as Head of State."},
    {"topic": "Government", "difficulty": "medium",
     "question": "The Australian Constitution can only be changed by:",
     "options": ["A vote in Parliament alone", "The Prime Minister",
                 "A successful national referendum", "A High Court ruling"],
     "correct": 2, "explanation": "Changes to the Constitution require a referendum with a national majority and a majority in at least four states."},
    {"topic": "Government", "difficulty": "easy",
     "question": "Australia’s federal Parliament is made up of:",
     "options": ["The President and Senate", "The House of Representatives and the Senate",
                 "Only the House of Representatives", "State Premiers and the Prime Minister"],
     "correct": 1, "explanation": "Federal Parliament has two houses: the House of Representatives and the Senate."},
    {"topic": "Flag & Symbols", "difficulty": "easy",
     "question": "Which star on the Australian national flag has seven points?",
     "options": ["The Southern Cross stars", "The Commonwealth Star",
                 "The Union Jack star", "The Indigenous Star"],
     "correct": 1, "explanation": "The Commonwealth Star has seven points — one for each state and one for the territories."},
    {"topic": "Flag & Symbols", "difficulty": "easy",
     "question": "Australia’s national floral emblem is the:",
     "options": ["Waratah", "Banksia", "Golden Wattle", "Eucalyptus"],
     "correct": 2, "explanation": "The Golden Wattle (Acacia pycnantha) is Australia’s national floral emblem."},
    {"topic": "History", "difficulty": "easy",
     "question": "Indigenous Australians (Aboriginal and Torres Strait Islander peoples) have lived in Australia for approximately:",
     "options": ["500 years", "5,000 years", "Tens of thousands of years", "Less than 200 years"],
     "correct": 2, "explanation": "Aboriginal and Torres Strait Islander peoples have lived in Australia for tens of thousands of years."},
    {"topic": "History", "difficulty": "medium",
     "question": "Australia became a federation of states on:",
     "options": ["26 January 1788", "1 January 1901", "25 April 1915", "11 November 1918"],
     "correct": 1, "explanation": "On 1 January 1901 the six colonies federated to form the Commonwealth of Australia."},
    {"topic": "History", "difficulty": "easy",
     "question": "ANZAC Day commemorates:",
     "options": ["Federation", "The landing of Australian and New Zealand troops at Gallipoli",
                 "The end of World War II", "Indigenous heritage"],
     "correct": 1, "explanation": "ANZAC Day on 25 April honours the ANZAC landing at Gallipoli in 1915 and all service since."},
    {"topic": "Geography", "difficulty": "easy",
     "question": "The capital city of Australia is:",
     "options": ["Sydney", "Melbourne", "Canberra", "Perth"],
     "correct": 2, "explanation": "Canberra in the Australian Capital Territory is Australia’s capital city."},
    {"topic": "Geography", "difficulty": "easy",
     "question": "Which is NOT a state of Australia?",
     "options": ["Queensland", "Northern Territory", "Victoria", "Tasmania"],
     "correct": 1, "explanation": "The Northern Territory is a territory, not a state. Australia has six states."},
    {"topic": "Responsibilities", "difficulty": "easy",
     "question": "Which of the following is a responsibility of Australian citizens?",
     "options": ["Voting in elections", "Wearing a uniform daily",
                 "Owning a house", "Speaking only English at home"],
     "correct": 0, "explanation": "Voting in federal, state and territory elections is a legal responsibility of citizens 18 and over."},
    {"topic": "Responsibilities", "difficulty": "medium",
     "question": "If called, Australian citizens have a duty to:",
     "options": ["Serve on a jury", "Donate to charity",
                 "Join the armed forces", "Move interstate"],
     "correct": 0, "explanation": "Serving on a jury when called is a civic responsibility of Australian citizens."},
    {"topic": "Rights", "difficulty": "easy",
     "question": "Australian citizens have the right to:",
     "options": ["Live and work permanently in Australia and apply for an Australian passport",
                 "Avoid paying any taxes", "Free overseas holidays from the government",
                 "Skip school as adults"],
     "correct": 0, "explanation": "Citizens may live and work permanently in Australia and apply for an Australian passport."},
    {"topic": "Indigenous Culture", "difficulty": "easy",
     "question": "The two distinct Indigenous peoples of Australia are:",
     "options": ["Maori and Aboriginal", "Aboriginal and Torres Strait Islander peoples",
                 "Pacific Islander and Aboriginal", "Polynesian and Melanesian"],
     "correct": 1, "explanation": "Australia’s First Peoples are Aboriginal peoples and Torres Strait Islander peoples."},
    {"topic": "Democracy", "difficulty": "medium",
     "question": "Voting in Australian federal elections is:",
     "options": ["Optional", "Compulsory for citizens 18 and over",
                 "Only for permanent residents", "Done by post only"],
     "correct": 1, "explanation": "Voting in federal elections is compulsory for Australian citizens aged 18 and over."},
    {"topic": "Democracy", "difficulty": "easy",
     "question": "Who is Australia’s Head of State?",
     "options": ["The Prime Minister", "The Governor-General",
                 "The Sovereign (King or Queen)", "The Speaker of the House"],
     "correct": 2, "explanation": "The Sovereign of Australia is the Head of State, represented in Australia by the Governor-General."},
    {"topic": "Laws", "difficulty": "easy",
     "question": "In Australia, the rule of law means:",
     "options": ["The Prime Minister is above the law", "All people, including governments, must obey the law",
                 "Only police follow laws", "Laws apply only on weekdays"],
     "correct": 1, "explanation": "Under the rule of law, everyone — including governments — is equally subject to the law."},
    {"topic": "Laws", "difficulty": "medium",
     "question": "Discrimination based on race, religion or sex in Australia is:",
     "options": ["Allowed in private workplaces", "Unlawful",
                 "Encouraged in some states", "Only unlawful in schools"],
     "correct": 1, "explanation": "Discrimination on the basis of race, religion, sex and other protected attributes is against the law."},
    {"topic": "National Identity", "difficulty": "easy",
     "question": "The Australian national anthem is:",
     "options": ["Waltzing Matilda", "Advance Australia Fair",
                 "God Save the King", "I Still Call Australia Home"],
     "correct": 1, "explanation": "‘Advance Australia Fair’ became Australia’s national anthem in 1984."},
    {"topic": "National Identity", "difficulty": "easy",
     "question": "Australia Day is celebrated on:",
     "options": ["1 January", "26 January", "25 April", "11 November"],
     "correct": 1, "explanation": "Australia Day is observed annually on 26 January."},
    {"topic": "Citizenship Pledge", "difficulty": "medium",
     "question": "The Australian Citizenship Pledge includes a commitment to:",
     "options": ["Speak only English", "Australia and its people, sharing democratic beliefs, rights and liberties",
                 "Serve in the army for two years", "Live in Canberra"],
     "correct": 1, "explanation": "The pledge commits you to Australia and its people, sharing its democratic beliefs, rights and liberties."},
    {"topic": "Three Levels of Government", "difficulty": "medium",
     "question": "The three levels of government in Australia are:",
     "options": ["Federal, state/territory and local", "Royal, federal and state",
                 "Federal, judicial and military", "Local, regional and national"],
     "correct": 0, "explanation": "Australia has federal (national), state/territory and local levels of government."},
    {"topic": "Three Levels of Government", "difficulty": "medium",
     "question": "Which level of government is generally responsible for rubbish collection and local roads?",
     "options": ["Federal", "State", "Local councils", "All three"],
     "correct": 2, "explanation": "Local councils typically manage rubbish collection, parks and local streets."},
    {"topic": "Migration", "difficulty": "easy",
     "question": "Australia is described as a:",
     "options": ["Monocultural society", "Multicultural society",
                 "Closed society", "Theocratic society"],
     "correct": 1, "explanation": "Australia is proudly multicultural — people from many cultures call it home."},
    {"topic": "Freedoms", "difficulty": "easy",
     "question": "Australians enjoy the freedom to:",
     "options": ["Speak openly within the limits of the law", "Break laws if they disagree with them",
                 "Refuse to follow road rules", "Avoid paying any tax"],
     "correct": 0, "explanation": "Freedom of speech is protected, subject to laws against defamation and incitement."},
    {"topic": "Government", "difficulty": "medium",
     "question": "Who appoints the Governor-General of Australia?",
     "options": ["The Prime Minister with advice from Cabinet, formally by the Sovereign",
                 "Parliament directly", "A national vote", "The High Court"],
     "correct": 0, "explanation": "The Sovereign appoints the Governor-General on the advice of the Australian Prime Minister."},
    {"topic": "Government", "difficulty": "easy",
     "question": "Members of the House of Representatives are elected for a term of approximately:",
     "options": ["1 year", "3 years", "6 years", "Life"],
     "correct": 1, "explanation": "Members of the House of Representatives serve up to three years."},
    {"topic": "Government", "difficulty": "medium",
     "question": "Senators are elected for terms of approximately:",
     "options": ["3 years", "4 years", "6 years", "10 years"],
     "correct": 2, "explanation": "Senators are usually elected for six-year terms."},
]

RSA_QUESTIONS = [
    {"topic": "Definitions", "difficulty": "easy",
     "question": "RSA stands for:",
     "options": ["Responsible Service of Alcohol", "Regulated Service of Alcohol",
                 "Restricted Sale of Alcohol", "Required Standards Authority"],
     "correct": 0, "explanation": "RSA stands for Responsible Service of Alcohol — the framework for legal and safe alcohol service."},
    {"topic": "Definitions", "difficulty": "easy",
     "question": "A ‘standard drink’ in Australia contains approximately:",
     "options": ["5 grams of pure alcohol", "10 grams of pure alcohol",
                 "20 grams of pure alcohol", "30 grams of pure alcohol"],
     "correct": 1, "explanation": "One Australian standard drink contains 10 g of pure alcohol."},
    {"topic": "Minor Service", "difficulty": "easy",
     "question": "The legal minimum age to be sold or supplied alcohol in licensed premises in Australia is:",
     "options": ["16", "17", "18", "21"],
     "correct": 2, "explanation": "It is unlawful to sell, supply or serve alcohol to anyone under 18 in Australia."},
    {"topic": "Minor Service", "difficulty": "medium",
     "question": "If you suspect a customer is under 18, you should:",
     "options": ["Serve them quickly to avoid argument", "Ask for an approved photo ID",
                 "Refuse but say nothing", "Ask another customer to vouch for them"],
     "correct": 1, "explanation": "Always check approved photo ID (driver licence, passport, proof-of-age card) for anyone who appears under 25."},
    {"topic": "Intoxication", "difficulty": "easy",
     "question": "Signs of intoxication include:",
     "options": ["Slurred speech, unsteady balance, aggressive or overly loud behaviour",
                 "Wearing bright clothing", "Ordering food",
                 "Sitting quietly"],
     "correct": 0, "explanation": "Slurred speech, poor coordination, loud or aggressive behaviour are common intoxication indicators."},
    {"topic": "Intoxication", "difficulty": "medium",
     "question": "Serving alcohol to a clearly intoxicated person is:",
     "options": ["Acceptable if they pay cash", "An offence under liquor laws",
                 "Allowed during happy hour", "OK if a friend asks for them"],
     "correct": 1, "explanation": "It is an offence to serve alcohol to an intoxicated person regardless of who pays."},
    {"topic": "Refusing Service", "difficulty": "medium",
     "question": "The best way to refuse service to an intoxicated patron is to:",
     "options": ["Loudly announce they are drunk", "Be polite, firm and explain the legal reason",
                 "Pretend the bar is closed", "Ignore them until they leave"],
     "correct": 1, "explanation": "Stay calm, polite, firm and explain you cannot serve them under RSA law."},
    {"topic": "Refusing Service", "difficulty": "medium",
     "question": "If a patron becomes aggressive after refusal of service, you should:",
     "options": ["Argue with them", "Alert management or security and stay calm",
                 "Serve them to keep the peace", "Lock the doors"],
     "correct": 1, "explanation": "Always notify management or security and avoid escalating the situation yourself."},
    {"topic": "Responsibilities", "difficulty": "easy",
     "question": "A licensee’s duty of care extends to:",
     "options": ["Only patrons inside the venue", "Patrons, staff and the broader community affected by the venue",
                 "Only adults over 21", "Only registered members"],
     "correct": 1, "explanation": "Duty of care includes patrons, staff and surrounding community impacted by the licensed premises."},
    {"topic": "Responsibilities", "difficulty": "easy",
     "question": "Free water must be made available to patrons:",
     "options": ["Only on weekends", "At all times alcohol is served",
                 "Only if requested in writing", "Only at lunchtimes"],
     "correct": 1, "explanation": "Free drinking water must be available whenever alcohol is being served."},
    {"topic": "Standard Drinks", "difficulty": "medium",
     "question": "Which of the following is approximately one standard drink?",
     "options": ["A 285 ml glass of full-strength beer (4.8%)",
                 "Half a bottle of wine", "A full pint of full-strength beer",
                 "A double shot of vodka"],
     "correct": 0, "explanation": "A 285 ml ‘middy/pot’ of full-strength beer (~4.8%) is approximately one standard drink."},
    {"topic": "Standard Drinks", "difficulty": "medium",
     "question": "A 30 ml nip of a spirit at 40% alcohol contains approximately:",
     "options": ["0.5 standard drinks", "1 standard drink",
                 "1.5 standard drinks", "2 standard drinks"],
     "correct": 1, "explanation": "A 30 ml nip of 40% spirit equals roughly one standard drink (10 g alcohol)."},
    {"topic": "ID Checks", "difficulty": "easy",
     "question": "Acceptable proof of age documents in Australia include:",
     "options": ["School ID card", "Library card",
                 "Australian driver licence, passport or approved proof-of-age card", "Credit card"],
     "correct": 2, "explanation": "Only government-issued photo ID such as driver licence, passport or proof-of-age cards are accepted."},
    {"topic": "ID Checks", "difficulty": "medium",
     "question": "If you suspect an ID is fake, you should:",
     "options": ["Accept it and serve them anyway", "Refuse service and follow venue policy on confiscation",
                 "Cut up the ID immediately", "Call the patron names"],
     "correct": 1, "explanation": "Refuse service and follow venue procedure. Confiscation rules vary by state."},
    {"topic": "Pregnancy", "difficulty": "easy",
     "question": "Health authorities advise that pregnant women should:",
     "options": ["Drink red wine only", "Not consume any alcohol",
                 "Drink lightly each evening", "Only drink at restaurants"],
     "correct": 1, "explanation": "Australian guidelines advise no alcohol during pregnancy as the safest option."},
    {"topic": "Promotions", "difficulty": "medium",
     "question": "Which alcohol promotion is generally PROHIBITED?",
     "options": ["A meal-and-drink deal", "Encouraging rapid or excessive consumption",
                 "Happy hour with reasonable conditions", "Free soft drinks"],
     "correct": 1, "explanation": "Promotions that encourage rapid or excessive drinking are not permitted under RSA principles."},
    {"topic": "Trading Hours", "difficulty": "medium",
     "question": "Selling alcohol outside the licensed trading hours is:",
     "options": ["Allowed for regulars", "A breach of the licence and an offence",
                 "OK if discounted", "Only an offence on Sundays"],
     "correct": 1, "explanation": "Trading outside permitted hours breaches the liquor licence and may result in penalties."},
    {"topic": "Intoxication", "difficulty": "easy",
     "question": "Which factor does NOT significantly affect a person’s blood alcohol concentration?",
     "options": ["Body weight", "Whether they have eaten",
                 "The colour of their shirt", "Gender"],
     "correct": 2, "explanation": "Shirt colour has no effect on BAC. Weight, food, gender, age and tolerance all do."},
    {"topic": "Intoxication", "difficulty": "medium",
     "question": "On average, the liver metabolises alcohol at a rate of about:",
     "options": ["One standard drink per hour", "Three standard drinks per hour",
                 "Half a standard drink per minute", "Ten standard drinks per hour"],
     "correct": 0, "explanation": "On average the liver processes roughly one standard drink per hour."},
    {"topic": "Safe Transport", "difficulty": "easy",
     "question": "If an intoxicated patron intends to drive home, you should:",
     "options": ["Let them leave quietly", "Offer to call a taxi, rideshare or arrange safe transport",
                 "Ignore the situation", "Sell them another drink to delay"],
     "correct": 1, "explanation": "RSA duty of care requires arranging safe transport such as taxi, rideshare or a sober friend."},
    {"topic": "Licensing", "difficulty": "easy",
     "question": "A liquor licence is required for:",
     "options": ["Drinking alcohol at home", "Selling or supplying alcohol commercially",
                 "Buying alcohol at a shop", "Pouring drinks at a private party of friends"],
     "correct": 1, "explanation": "Anyone selling or supplying alcohol commercially must hold an appropriate liquor licence."},
    {"topic": "Licensing", "difficulty": "medium",
     "question": "Penalties for breaching RSA laws can include:",
     "options": ["Only a small warning", "Fines, loss of licence and personal prosecution",
                 "A free counselling session", "Nothing significant"],
     "correct": 1, "explanation": "Breaches can lead to substantial fines, suspension or loss of licence, and personal criminal liability."},
    {"topic": "Mixing Drugs", "difficulty": "medium",
     "question": "Mixing alcohol with illicit or prescription drugs can:",
     "options": ["Reduce intoxication", "Cause unpredictable and dangerous effects",
                 "Only affect mood", "Always be safe with food"],
     "correct": 1, "explanation": "Combining alcohol with drugs can produce dangerous, sometimes fatal, interactions."},
    {"topic": "Service Practices", "difficulty": "easy",
     "question": "‘Topping up’ a customer’s glass before it is empty:",
     "options": ["Is good customer service always",
                 "Should be avoided because it disguises actual consumption",
                 "Earns extra tips", "Is required by law"],
     "correct": 1, "explanation": "Topping up makes it difficult to monitor how much a patron has consumed and is discouraged."},
    {"topic": "Service Practices", "difficulty": "medium",
     "question": "Offering substantial low- and no-alcohol options is a key RSA strategy because it:",
     "options": ["Increases profits only", "Provides safer alternatives and supports moderation",
                 "Is required to be free", "Helps avoid licence fees"],
     "correct": 1, "explanation": "Offering low/no-alcohol drinks supports moderation and reduces the risk of intoxication."},
    {"topic": "Approaching Customers", "difficulty": "medium",
     "question": "When monitoring a patron’s level of intoxication, you should:",
     "options": ["Wait until they fall over", "Observe behaviour, speech and coordination throughout service",
                 "Only check when management asks", "Rely on the patron self-reporting"],
     "correct": 1, "explanation": "Active observation throughout service helps identify early signs of intoxication."},
    {"topic": "Domestic Violence", "difficulty": "medium",
     "question": "If you see signs of a patron being harassed or unsafe at the venue, you should:",
     "options": ["Mind your own business", "Discreetly check on them and involve management or police if needed",
                 "Loudly call them out", "Ignore unless they ask for help"],
     "correct": 1, "explanation": "Staff have a duty of care — discreetly assist and escalate to management or police when necessary."},
    {"topic": "House Policies", "difficulty": "easy",
     "question": "‘House policies’ at a licensed venue are:",
     "options": ["Optional decoration", "Internal rules supporting the licence and RSA practices",
                 "Suggestions for customers", "Only for VIP patrons"],
     "correct": 1, "explanation": "House policies are formal venue rules that reinforce RSA and licensing obligations."},
    {"topic": "Documentation", "difficulty": "medium",
     "question": "An incident involving refusal of service or intoxication should be:",
     "options": ["Forgotten quickly", "Recorded in the venue’s incident register with details and time",
                 "Posted on social media", "Discussed only verbally"],
     "correct": 1, "explanation": "All significant incidents should be logged in the incident register for legal and review purposes."},
    {"topic": "Ongoing Training", "difficulty": "easy",
     "question": "RSA certification in most Australian states requires:",
     "options": ["No refresher ever", "Periodic refresher training as per state regulation",
                 "Refresher every 10 years", "Only on changing employers"],
     "correct": 1, "explanation": "Most states require periodic RSA refresher courses; check your local rules for timing."},
]


CATEGORIES = [
    {
        "id": "dkt",
        "name": "Driver Knowledge Test",
        "short_name": "DKT",
        "description": "Australian learner driver knowledge — road rules, signs, safety.",
        "icon": "car-sport",
        "color": "#00D1FF",
        "total_questions_in_exam": 25,
        "time_limit_minutes": 30,
        "pass_score_percent": 80,
        "questions": DKT_QUESTIONS,
    },
    {
        "id": "citizenship",
        "name": "Australian Citizenship Test",
        "short_name": "Citizenship",
        "description": "Australian values, history, government and national identity.",
        "icon": "flag",
        "color": "#00FF9D",
        "total_questions_in_exam": 20,
        "time_limit_minutes": 25,
        "pass_score_percent": 75,
        "questions": CITIZENSHIP_QUESTIONS,
    },
    {
        "id": "rsa",
        "name": "Responsible Service of Alcohol",
        "short_name": "RSA",
        "description": "Legal and responsible service of alcohol in Australia.",
        "icon": "wine",
        "color": "#FF8F00",
        "total_questions_in_exam": 20,
        "time_limit_minutes": 25,
        "pass_score_percent": 75,
        "questions": RSA_QUESTIONS,
    },
]
