import { LegalScreen } from "@/src/components/LegalScreen";

export default function Disclaimer() {
  return (
    <LegalScreen
      testID="disclaimer-screen"
      title="Disclaimer"
      intro="Important information about Passaroo and how our practice content relates to official Australian exams."
      sections={[
        {
          heading: "Independent platform",
          body:
            "Passaroo is an independent educational platform and is not affiliated with Australian government agencies, state road authorities, the Department of Home Affairs, or any official examination body.",
        },
        {
          heading: "Practice content only",
          body:
            "All questions, explanations, flashcards, study plans, and AI-generated content available in Passaroo are independently created for practice and preparation purposes only. They may differ in wording, structure, scope, or weighting from the official exams.",
        },
        {
          heading: "No guarantee of passing",
          body:
            "Using Passaroo does not guarantee that you will pass any official examination. Real exams may change without notice. Always confirm current rules, fees and procedures with the official issuing authority before sitting an exam.",
        },
        {
          heading: "AI-generated information",
          body:
            "AI explanations and tutor replies are generated by a large language model and may occasionally contain errors. Treat them as study aids and verify safety-critical or legal information against official sources.",
        },
        {
          heading: "Australian Consumer Law",
          body:
            "Nothing in this disclaimer excludes or limits your rights under the Australian Consumer Law.",
        },
      ]}
    />
  );
}
