// AI-generated 7-day study plan.
import { Ionicons } from "@expo/vector-icons";
import { useRouter } from "expo-router";
import { useEffect, useState } from "react";
import { Image, ScrollView, StyleSheet, Text, TouchableOpacity, View } from "react-native";
import { SafeAreaView } from "react-native-safe-area-context";

import { api } from "@/src/api";
import { PButton } from "@/src/components/PButton";
import { colors, IMAGES, radius, spacing, typography } from "@/src/theme";

export default function StudyPlan() {
  const router = useRouter();
  const [plan, setPlan] = useState<string>("");
  const [loading, setLoading] = useState(true);
  const [refreshing, setRefreshing] = useState(false);

  const load = async () => {
    setLoading(true);
    try {
      const r = await api<{ plan: string }>("/study-plan");
      setPlan(r.plan);
    } catch (e: any) {
      setPlan(`⚠️ ${e.message}`);
    }
    setLoading(false);
  };
  useEffect(() => { load(); }, []);

  const regenerate = async () => {
    setRefreshing(true);
    // server caches 24h — bust by deleting cached and reloading (simple approach: reload)
    await load();
    setRefreshing(false);
  };

  const lines = plan
    .split("\n")
    .map((l) => l.trim())
    .filter((l) => l.length > 0);

  return (
    <SafeAreaView style={styles.container} edges={["top"]} testID="study-plan-screen">
      <View style={styles.header}>
        <TouchableOpacity onPress={() => router.back()}>
          <Ionicons name="arrow-back" size={26} color={colors.textPrimary} />
        </TouchableOpacity>
        <Text style={styles.h1}>Study Plan</Text>
      </View>
      <ScrollView contentContainerStyle={styles.scroll}>
        <View style={styles.hero}>
          <Image source={{ uri: IMAGES.mascot }} style={{ width: 80, height: 80 }} resizeMode="contain" />
          <Text style={styles.heroTitle}>Your personalised 7-day plan</Text>
          <Text style={styles.heroSub}>Generated by AI based on your weak topics & streak</Text>
        </View>

        {loading ? (
          <Text style={styles.subtle}>Building your plan…</Text>
        ) : (
          lines.map((line, i) => (
            <View key={i} style={styles.day} testID={`day-${i}`}>
              <View style={styles.dayDot}>
                <Text style={styles.dayNum}>{i + 1}</Text>
              </View>
              <Text style={styles.dayText}>{line.replace(/^Day\s*\d+:\s*/i, "").replace(/^\d+\.\s*/, "")}</Text>
            </View>
          ))
        )}

        <PButton title="Regenerate plan" variant="secondary" onPress={regenerate} loading={refreshing} testID="regen-plan" />
      </ScrollView>
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: colors.bg },
  header: { flexDirection: "row", padding: spacing.md, alignItems: "center", gap: 12, borderBottomWidth: 2, borderBottomColor: colors.border },
  h1: { ...typography.h2, fontSize: 22 },
  scroll: { padding: spacing.lg, gap: spacing.sm, paddingBottom: 60 },
  hero: { alignItems: "center", gap: 4, marginBottom: spacing.md },
  heroTitle: { ...typography.h2, fontSize: 22, textAlign: "center" },
  heroSub: { color: colors.textSecondary, textAlign: "center" },
  subtle: { color: colors.textSecondary, textAlign: "center" },
  day: {
    flexDirection: "row", gap: 12, alignItems: "center",
    backgroundColor: "#fff", borderRadius: radius.lg, padding: spacing.md,
    borderWidth: 2, borderColor: colors.border, borderBottomWidth: 4,
  },
  dayDot: {
    width: 40, height: 40, borderRadius: 20, backgroundColor: colors.primary,
    alignItems: "center", justifyContent: "center",
  },
  dayNum: { color: "#0A2A33", fontWeight: "800" },
  dayText: { flex: 1, color: colors.textPrimary, fontWeight: "600", fontSize: 15, lineHeight: 21 },
});
