import { LegalScreen } from "@/src/components/LegalScreen";

export default function Terms() {
  return (
    <LegalScreen
      testID="terms-screen"
      title="Terms of Service"
      intro="By creating an account or using Passaroo, you agree to these Terms. Please read them carefully — they explain your rights and obligations as a user of our independent educational platform."
      sections={[
        {
          heading: "1. Independent platform — not a government service",
          body:
            "Passaroo is an independent educational platform. We are not affiliated with, endorsed by, or connected to any Australian government department, state road authority, the Department of Home Affairs, examination bodies, or any official testing organisation. All questions on the platform are independently created for practice and preparation purposes and may differ from the official exams.",
        },
        {
          heading: "2. Eligibility",
          body:
            "You must be at least 16 years old to create an account. By signing up you confirm that the information you provide is accurate and that you are using the app for personal exam-preparation purposes.",
        },
        {
          heading: "3. Your account",
          body:
            "You are responsible for maintaining the confidentiality of your account credentials. One account is for one person — account sharing, transfer, or sale is prohibited. Each account is limited to one active device session at a time; signing in on a new device will sign you out of the previous one.",
        },
        {
          heading: "4. Subscriptions & billing",
          body:
            "Premium and Pro subscriptions are billed through the Apple App Store or Google Play. Your subscription auto-renews at the end of each billing period unless you cancel at least 24 hours before the renewal date. Manage cancellations from your app-store subscription settings. See our Refund Policy for details on refunds.",
        },
        {
          heading: "5. Fair use",
          body:
            'Pro is marketed as “Unlimited Practice Exams” but is subject to fair-use protections (currently capped at 50 exams per week) to keep the service available for everyone. AI features (explanations, tutor chat, flashcards) are similarly subject to per-minute and per-day fair-use limits that scale with your plan.',
        },
        {
          heading: "6. Acceptable use",
          body:
            "You must not: (a) attempt to bypass paywalls, rate limits, or fair-use controls; (b) scrape, mirror, or republish exam questions, AI replies, or any in-app content; (c) automate access to the API using bots or scripts; (d) share your account credentials; (e) use the app to engage in academic dishonesty in any real-world exam. Violations may result in suspension or termination without refund.",
        },
        {
          heading: "7. AI-generated content",
          body:
            "Explanations, study plans, flashcards, and tutor responses are generated by an AI model. While we work hard to keep them accurate and aligned with publicly available study material, you must verify critical information against official government sources before sitting any real exam. AI replies may occasionally contain errors.",
        },
        {
          heading: "8. Intellectual property",
          body:
            "All Passaroo branding, design, original question banks, and AI-generated study materials are owned by Passaroo or its licensors. You may use them only inside the app for personal study; redistribution, reproduction, or commercial use is prohibited.",
        },
        {
          heading: "9. Service availability",
          body:
            "We provide the app on an “as-is” basis. We do not guarantee uninterrupted access, error-free operation, or that you will pass any official exam after using Passaroo. We may modify, suspend, or discontinue features at any time.",
        },
        {
          heading: "10. Limitation of liability",
          body:
            "To the extent permitted by Australian law, Passaroo is not liable for any indirect, incidental, or consequential damages arising from your use of the app, including missed examinations, failed exams, or loss of study data. Our maximum liability is limited to the amount you paid us in the previous 12 months.",
        },
        {
          heading: "11. Termination",
          body:
            "We may suspend or close accounts that violate these Terms, abuse fair-use protections, scrape content, automate access, share accounts, or otherwise compromise the service — without refund. You can delete your account at any time from Profile → Delete My Account & Data.",
        },
        {
          heading: "12. Governing law",
          body:
            "These Terms are governed by the laws of Australia. Disputes will be resolved in the courts of Australia. Nothing in these Terms excludes your non-excludable rights under the Australian Consumer Law.",
        },
        {
          heading: "13. Changes to these Terms",
          body:
            "We may update these Terms from time to time. Material changes will be announced inside the app. Continued use after the changes take effect means you accept the updated Terms.",
        },
        {
          heading: "14. Contact",
          body:
            "Questions about these Terms? Email support@passaroo.app.",
        },
      ]}
    />
  );
}
